name: Sign and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building Firefox Add-on
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          npm install -g web-ext
          web-ext sign --api-key=${{secrets.MOZ_API_KEY}} --api-secret=${{secrets.MOZ_API_SEC}}
        working-directory: ./firefox

      - name: list files
        working-directory: ./firefox
        run: ls -la web-ext-artifacts
